config/routes.rb
Rails.application.routes.draw do
  mount Peek::Railtie           => 'peek' if PeekBar.available?
  mount LetterOpenerWeb::Engine => 'mail' if Rails.env.development?

  devise_for :user, skip: [:sessions, :passwords, :registrations, :unlocks]

  devise_scope :user do
    get  'login',  to: 'devise/sessions#new', as: 'new_login'
    post 'login',  to: 'devise/sessions#create'
    get  'logout', to: 'devise/sessions#destroy'

    scope :my do
      scope :account do
        resource :password, controller: 'devise/passwords', except: [:show, :destroy]
        resource :unlock,   controller: 'devise/unlocks',   only:   [:create, :new, :show]
      end
    end

    resource :join, controller: 'user_registrations', except: [:show, :new] do
      member do
        get 'cancel'
      end
    end
    get '/join', to: 'user_registrations#new', as: 'new_join'

    resources :organizations
  end

  mount JasmineRails::Engine => '/dev/specs' if defined?(JasmineRails)
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  has_many :kegs,
           inverse_of: :beer

  belongs_to :brewery,
             inverse_of: :beers
  belongs_to :beer_style,
             inverse_of: :beers
end

app/models/beer_style.rb
class BeerStyle < ActiveRecord::Base
  has_many :beers,
           inverse_of: :beer_style
  has_many :breweries,
           through:    :beers,
           inverse_of: :beer_styles
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :beers,
           inverse_of: :brewery
  has_many :beer_styles,
           through:    :beers,
           inverse_of: :brewries
end

app/models/keg.rb
class Keg < ActiveRecord::Base
  has_one :venue_tap,
          inverse_of: :keg

  belongs_to :venue,
             inverse_of: :kegs
  belongs_to :beer,
             inverse_of: :kegs
  belongs_to :keg_volume,
             inverse_of: :kegs
end

app/models/keg_volume.rb
# TODO: Seed data for keg volume specifications: https://en.wikipedia.org/wiki/Keg#Beer_keg
class KegVolume < ActiveRecord::Base
  has_many :kegs,
           inverse_of: :keg_volume
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :organization_users,
           inverse_of: :organization
  has_many :organization_roles,
           through:    :organization_users,
           inverse_of: :organizations

  with_role_extension = proc do
    extending Factory::WithRoleExtension.build(
      mapping_association: :organization_users,
      role_association:    :organization_role
    )
  end
  has_many :users, with_role_extension,
           through:    :organization_users,
           inverse_of: :organizations

  has_many :venues,
           inverse_of: :organization
end

app/models/organization_role.rb
class OrganizationRole < ActiveRecord::Base
  has_many :organization_users,
           inverse_of: :organization_role
  has_many :users,
           through:    :organization_users,
           inverse_of: :organization_roles
  has_many :organizations,
           through:    :organization_users,
           inverse_of: :organization_roles

  def self.owner
    find_or_create_by(name: 'owner')
  end
end

app/models/organization_user.rb
class OrganizationUser < ActiveRecord::Base
  belongs_to :user,
             inverse_of: :organization_users
  belongs_to :organization,
             inverse_of: :organization_users
  belongs_to :organization_role,
             inverse_of: :organization_users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_paper_trail

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable, :timeoutable

  # ActiveJob Compatibility
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  has_many :organization_users,
           inverse_of: :user
  has_many :organization_roles,
           through:    :organization_users,
           inverse_of: :users

  with_role_extension = proc do
    extending Factory::WithRoleExtension.build(
      mapping_association: :organization_users,
      role_association:    :organization_role
    )
  end
  has_many :organizations, with_role_extension,
           through:    :organization_users,
           inverse_of: :users
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :kegs,
           inverse_of: :venue
  has_many :venue_taps,
           inverse_of: :venue

  belongs_to :organization,
             inverse_of: :venues
end

app/models/venue_tap.rb
class VenueTap < ActiveRecord::Base
  belongs_to :venue,
             inverse_of: :venue_taps
  belongs_to :keg,
             inverse_of: :venue_tap
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include DeviseHelper

  ensure_security_headers
  protect_from_forgery with: :exception

  private

  def id
    @_id ||= params[:id]
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  after_action :verify_policy_scoped, only: [:index, :show]
  after_action :verify_authorized

  def index
    authorize @organizations = organizations
  end

  def new
    authorize @form = form
  end

  def create
    authorize creator.form.model

    creator.call do |result|
      @form = result.service.form
      redirect_to @form, notice: 'Organization created!' if result.success?
      render action: :new if result.error?
    end
  end

  def show
    authorize @organization = organization
  end

  private

  def organizations
    policy_scope(Organization)
  end

  def organization
    return Organization.new unless id
    policy_scope(Organization).find(id)
  end

  def form
    @_form ||= OrganizationForm.new(organization)
  end

  def creator
    @_creator ||= Organization::Creator.new(
      user:   current_user,
      params: params[:organization],
      form:   form
    )
  end
end

app/controllers/user_registrations_controller.rb
class UserRegistrationsController < Devise::RegistrationsController
  def sign_up(resource_name, resource)
    welcome_user(resource) if super
  end

  private

  def welcome_user(user)
    User::Welcomer.new(user: user).call
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def new_session_path(*_args)
    new_login_path
  end
end

app/helpers/peek_bar_helper.rb
module PeekBarHelper
  # Typical Peek Integration
  def peek_enabled?
    PeekBar.enabled?(current_user)
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title= t('app.name')
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    - if peek_enabled?
      = stylesheet_link_tag 'peek_bar', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'shared/head/favicon'
  body class=yield(:body_class)
    = render 'shared/layout/superuser'
    = render 'shared/layout/navbar'

    .content
      .container
        .row: .col-md-12= cell(:flash, flash).call(:list)
        .row: .col-md-12= yield

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    - if peek_enabled?
      = javascript_include_tag 'peek_bar', 'data-turbolinks-track' => true

    = render 'peek/bar' if peek_enabled?

app/views/organizations/index.html.slim
h1
  | Organizations
  small.pull-right
    = link_to "New Organization", new_organization_path, class: 'btn btn-info'

ul.organizations
  - @organizations.each do |organization|
    li.organization= link_to organization.name, organization, class: 'url'

app/views/organizations/new.html.slim
= simple_form_for @form do |f|
  = f.input :name
  = f.submit

app/views/organizations/show.html.slim
h1
  span.name= @organization.name
  small< Organization

.row
  .col-md-2
    strong Users
  .col-md-10
    ul.list-unstyled
      - @organization.organization_users.each do |org_user|
        li= "#{org_user.user.email} (#{org_user.organization_role.name})"

app/views/pages/home.html.slim
- content_for :body_class
  | home page

.row
  .col-md-6
    .pitch
      .page-header
        h1 Always know what's on tap.
      ul
        li Keep your tap list up to date.
        li Automatically tell people when taps change.
        li Sit back and enjoy a beer.
      p: big: strong: em Cheers!
  .col-md-6
    = cell(:brand, :home).call(:show)

app/views/shared/head/_favicon.html.slim
link href=asset_url('favicon.ico') rel=("shortcut icon") /
link href=asset_url('favicon.ico') rel="icon" sizes=("16x16 32x32") /

app/views/shared/layout/_navbar.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-target="#main-navbar-collapse" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = cell(:brand).call
    #main-navbar-collapse.collapse.navbar-collapse
      ul.nav.navbar-nav
        li= link_to "Organizations", organizations_path
      ul.nav.navbar-nav.navbar-right
        = render 'shared/layout/navbar_account'
        = render 'shared/layout/navbar_development' if Rails.env.development?

app/views/shared/layout/_navbar_account.html.slim
li
  - if current_user
    li.dropdown
      a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button"
        = current_user.email
        span.caret
      ul.dropdown-menu role="menu"
        li= link_to "Stuff...", "#"
        li.divider
        li= link_to "Log out", logout_path
  - else
    = link_to "Log in", new_login_path

app/views/shared/layout/_navbar_development.html.slim
li.dropdown
  a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button"
    | Development
    span.caret
  ul.dropdown-menu role="menu"
    li= link_to raw("Super User&hellip;"), '#', data: {visibility: '#superuser-tools'}
    li.divider
    li= link_to "Mail", letter_opener_web_path, target: '_mail'
    li= link_to "Coverage", 'file://' + File.join(Rails.root, 'reports/coverage/index.html'), target: '_coverage'
    li= link_to "Jasmine Specs", jasmine_rails_path, target: "_jasmine"
    li.divider
    li= link_to "GitHub", "https://github.com/cwest/not", target: "_github"
    li= link_to "Pull Requests", "https://github.com/cwest/not/pulls", target: "_pulls"
    li= link_to "Travis CI", "https://travis-ci.org/cwest/not", target: "_travis"
    li= link_to "Gemnasium", "https://gemnasium.com/cwest/not", target: "_gemnasium"

app/views/shared/layout/_superuser.html.slim
#superuser-tools.superuser-tools
  .container
    .row
      .col-sm-7
      .col-sm-5
        .pull-right
          .tool
            form: label
              ' Switch User
              = switch_user_select